### ISSUE TITLE
Publicar versão 1.0 da aplicação

### ISSUE THREAD

**Issue by karolinemc** [super-poderosas/caixadememorias#37]

**Comment by GeovanaF6** [comment]
Requisitos funcionais:

 

- [x] O jogo deve ser planejado para suportar interação através de várias mídias assíncronas: texto, áudio e vídeo https://github.com/boidacarapreta/adcipt20222/issues/7.

- [x]  O jogo deve ter suporte a mídia síncrona: áudio sobre WebRTC https://github.com/boidacarapreta/adcipt20222/issues/32.

- [x]  Rodar aplicação em servidor virtual https://github.com/boidacarapreta/adcipt20222/issues/18.

- [x]  Persistir dados dos jogadores em banco de dados não relacional https://github.com/boidacarapreta/adcipt20222/issues/22.
